sudo: required
services:
  - docker

before_install:
  - docker build -t ybaeofco/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ybaeofco/react-test npm test -- --coverage

after_success:
  - docker build -t ybaeofco/multi-client ./client
  - docker build -t ybaeofco/multi-nginx ./nginx 
  - docker build -t ybaeofco/multi-server ./server 
  - docker built -t ybaeofco/multi-worker ./worker 
  # Login in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Taje images and push them to Docker Hub
  - docker push ybaeofco/multi-client
  - docker push ybaeofco/multi-nginx
  - docker push ybaeofco/multi-server 
  - docker push ybaeofco/multi-worker